apiVersion: v1
kind: ReplicationController
metadata:
  name: shiv-rc
spec:
  replicas: 3
selector:
    app: myapp
    version: 2.6.2
template:
    metadata:
        labels:
        app: myapppod
        version: 2.6.2
containers:
        - name: mynginx
          image: nginx
          ports: 
          - container: 80